language: php

matrix:
  include:
    - php: "7.2"
      env: DOKUWIKI=master
    - php: "7.2"
      env: DOKUWIKI=release_stable_2018-04-22a
    - php: "7.1"
      env: DOKUWIKI=master
    - php: "7.1"
      env: DOKUWIKI=release_stable_2018-04-22a
    - php: "7.0"
      env: DOKUWIKI=master
    - php: "7.0"
      env: DOKUWIKI=release_stable_2018-04-22a
    - php: "5.6"
      env: DOKUWIKI=master
    - php: "5.6"
      env: DOKUWIKI=release_stable_2018-04-22a
    - php: "5.6"
      env: DOKUWIKI=release_stable_2017-02-19e
    - php: "5.6"
      env: DOKUWIKI=release_stable_2016-06-26e
    - php: "5.6"
      env: DOKUWIKI=release_stable_2015-08-10a

before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install: sh travis.sh
script: 
  - cd _test
  - ./phpunit.phar --group plugin_tagfilter
